underwaterOverlay=true
oldLighting=false
vignette=true
oldHandLight=true

sliders=SCALE BAYER_SIZE POSTERIZING_AMOUNT

texture.composite.colortex4=tex/bluenoise.png

screen = \
    DITHERING_STYLE [ORDERED] \
    POSTERIZING_AMOUNT SCALE

screen.ORDERED = \
    BAYER_SIZE BAYER_STYLE